# Generated by Django 6.0.3 on 2026-03-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigninvite'),
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_sources', to='campaigns.campaign')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium.source')),
            ],
            options={
                'unique_together': {('campaign', 'source')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='sources',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignSource', to='compendium.source'),
        ),
    ]
