# Generated by Django 6.0.3 on 2026-04-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spell_level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('casting_type', models.CharField(choices=[('ACTION', 'Action'), ('BONUS_ACTION', 'Bonus Action'), ('REACTION', 'Reaction'), ('TIME', 'Time-based'), ('SPECIAL', 'Special')], max_length=20)),
                ('casting_value', models.IntegerField(blank=True, null=True)),
                ('casting_unit', models.CharField(blank=True, choices=[('MINUTE', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day')], max_length=20, null=True)),
                ('range_type', models.CharField(choices=[('SELF', 'Self'), ('TOUCH', 'Touch'), ('DISTANCE', 'Distance'), ('SPECIAL', 'Special')], max_length=20)),
                ('range_value', models.IntegerField(blank=True, null=True)),
                ('range_unit', models.CharField(blank=True, choices=[('FT', 'Feet'), ('MI', 'Mile')], max_length=10, null=True)),
                ('range_area_type', models.CharField(blank=True, choices=[('LINE', 'Line'), ('CONE', 'Cone'), ('CUBE', 'Cube'), ('SPHERE', 'Sphere'), ('CYLINDER', 'Cylinder'), ('EMANATION', 'Emanation')], max_length=10, null=True)),
                ('range_area_value', models.IntegerField(blank=True, null=True)),
                ('range_area_unit', models.CharField(blank=True, choices=[('FT', 'Feet'), ('MI', 'Mile')], max_length=10, null=True)),
                ('duration_type', models.CharField(choices=[('INSTANT', 'Instant'), ('ROUND', 'Round'), ('TIME', 'Time-based'), ('SPECIAL', 'Special')], max_length=20)),
                ('duration_value', models.IntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('MINUTE', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day')], max_length=20, null=True)),
                ('concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('verbal_component', models.BooleanField(default=False)),
                ('somatic_component', models.BooleanField(default=False)),
                ('material_component', models.TextField(blank=True)),
                ('school', models.CharField(choices=[('ABJ', 'Abjuration'), ('CONJ', 'Conjuration'), ('DIV', 'Divination'), ('ENCH', 'Enchantment'), ('EVOC', 'Evocation'), ('ILL', 'Illusion'), ('NECRO', 'Necromancy'), ('TRANS', 'Transmutation')], max_length=10)),
                ('description', models.TextField()),
                ('classes', models.ManyToManyField(related_name='spells', to='compendium.characterclass')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
